version: '2'
services:
  artifactory:
    image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:4.8.0
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory/data
    ports:
      - "8081:8081"
volumes:
  artifactory_data: {}
