version: '2'
services:
  artifactory:
    image: jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:4.8.0
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory/data
    ports:
      - "8081:8081"
  vagrant_proxy:
    build:
      context: ./
    depends_on:
      - artifactory
    image: mkuzmin/vagrant-proxy
    environment:
      artifactoryUrl: http://artifactory:8081/artifactory/
      repository: vagrant
      organization: org
      redirectUrl: http://www.google.com
    ports:
      - "8080:8080"
volumes:
  artifactory_data:
